/* eslint-disable @typescript-eslint/no-explicit-any */

import { MenuSection } from '@/lib/types/menu';
import {
  LayoutDashboard,
  Heart,
  Mail,
  UserPlus,
  Contact,
  FolderOpen,
  Calendar,
  Target,
  DollarSign,
  Package,
  PackageSearch,
  Truck,
  Search,
  Building2,
  MapPin,
  Shield,
  Fuel,
  Users,
  UserCheck,
  Upload,
  Settings,
  TrendingUp,
  Receipt,
  CreditCard,
  Calculator,
  PiggyBank,
  Clock,
  FileText,
  Banknote,
  Code,
  Bug,
  Zap,
  Store,
  ShieldAlert,
  Cpu,
  BarChart3,
  Plus,
  CheckCircle,
  RotateCcw,
  ShoppingCart,
  Landmark,
  BookOpen,
  Book,
  Scale,
  LineChart,
  Archive,
  Building,
  TrendingDown,
  Globe,
  Activity,
  AlertTriangle,
  XCircle,
  Repeat,
  FileBarChart,
  CircleDollarSign,
  History,
  Wallet,
  HandCoins,
  ClipboardList,
  Wrench,
  PieChart,
  Coins,
  Building as TaxBuilding,
  Target as TaxTarget
} from "lucide-react";

export const CARRIER_ADMIN_MENU: MenuSection = {
  items: [
    {
      title: "Dashboard",
      icon: LayoutDashboard,
      path: "/dashboard",
    },
    {
      title: "Relationships",
      icon: Heart,
      subMenu: [
        { title: "Overview", icon: LayoutDashboard, path: "/crm/overview" },
        { title: "Email", icon: Mail, path: "/crm/emails" },
        { title: "Leads", icon: UserPlus, path: "/crm/leads" },
        { title: "Contacts", icon: Contact, path: "/crm/contacts" },
        { title: "Projects", icon: FolderOpen, path: "/crm/projects" },
        { title: "Calendar", icon: Calendar, path: "/crm/calendar" },
        { title: "Opportunities", icon: Target, path: "/crm/opportunities" },
      ],
    },
    {
      title: "Quote",
      icon: DollarSign,
      subMenu: [
        { title: "All Quote", icon: FileText, path: "/quotes/all" },
        { title: "New Quote", icon: UserPlus, path: "/quotes/new" },
      ],
    },
    {
      title: "Shipments",
      icon: Package,
      subMenu: [
        { title: "All Shipments", icon: Package, path: "/shipments" },
        { title: "New Shipments", icon: Plus, path: "/shipments/new" },
        { title: "Assigned", icon: UserCheck, path: "/shipments/assigned" },
        { title: "Pending", icon: Clock, path: "/shipments/pending" },
        { title: "In Transit", icon: Truck, path: "/shipments/in-transit" },
        { title: "Delivered", icon: CheckCircle, path: "/shipments/delivered" },
      ],
    },
    {
      title: "Load Board",
      icon: PackageSearch,
      subMenu: [
        { title: "Find Loads", icon: Search, path: "/loadboard/find" },
        { title: "Search Loads", icon: PackageSearch, path: "/loadboard/search" },
        { title: "Post Truck", icon: Truck, path: "/loadboard/post-truck" },
        { title: "My Load", icon: Package, path: "/loadboard/my-loads" },
      ],
    },
    {
      title: "Networks",
      icon: Building2,
      subMenu: [
        { title: "Customers", icon: Users, path: "/networks/customers" },
        { title: "Carriers", icon: Truck, path: "/networks/carriers" },
        { title: "Vendors", icon: Package, path: "/networks/vendors" },
        { title: "Terminals", icon: Building2, path: "/networks/terminals" },
        { title: "Locations", icon: MapPin, path: "/networks/locations" },
        { title: "Invoices", icon: Receipt, path: "/networks/invoices" },
      ],
    },
    {
      title: "Assets",
      icon: Truck,
      subMenu: [
        { title: "Units", icon: Package, path: "/assets/units" },
        { title: "Trucks", icon: Truck, path: "/assets/trucks" },
        { title: "Trailers", icon: Truck, path: "/assets/trailers" },
        { title: "Fleet Tracker", icon: MapPin, path: "/assets/fleet-tracker" },
        { title: "Compliance", icon: Shield, path: "/assets/compliance" },
        { title: "Fuel Audit", icon: Fuel, path: "/assets/fuel-audit" },
      ],
    },
    {
      title: "Workers",
      icon: Users,
      subMenu: [
        { title: "Executive", icon: UserCheck, path: "/carrier-admin/workers/executive" },
        { title: "Employee", icon: Users, path: "/carrier-admin/workers/employee" },
        { title: "Agents", icon: UserPlus, path: "/carrier-admin/workers/agents" },
        { title: "Drivers", icon: Truck, path: "/carrier-admin/workers/drivers" },
        { title: "Owner Operators", icon: Building2, path: "/carrier-admin/workers/owner-operators" },
      ],
    },
    {
      title: "Documents",
      icon: FileText,
      subMenu: [
        { title: "All Documents", icon: FolderOpen, path: "/documents/all" },
        { title: "Upload", icon: Upload, path: "/documents/upload" },
        { title: "Setup", icon: Settings, path: "/documents/setup" },
      ],
    },
    {
      title: "Rates",
      icon: TrendingUp,
      subMenu: [
        { title: "Overview", icon: TrendingUp, path: "/carrier-admin/rates" },
        { title: "Buy Rates", icon: DollarSign, path: "/carrier-admin/rates/buy" },
        { title: "Sell Rates", icon: TrendingUp, path: "/carrier-admin/rates/sell" },
        { title: "Fuel Surcharge", icon: Fuel, path: "/carrier-admin/rates/fuel" },
        { title: "Accessorial", icon: Package, path: "/carrier-admin/rates/accessorial" },
        { title: "Margin Analysis", icon: BarChart3, path: "/carrier-admin/rates/margin" },
        { title: "Target Rates", icon: Target, path: "/carrier-admin/rates/target" },
      ],
    },
    {
      title: "Financials",
      icon: DollarSign,
      subMenu: [
        { title: "Sales & Payments", icon: Receipt, path: "/financials/sales" },
        { title: "Purchases", icon: ShoppingCart, path: "/financials/purchases" },
        { title: "Accounting", icon: Calculator, path: "/financials/accounting" },
        { title: "Payroll", icon: Users, path: "/financials/payroll" },
        { title: "Reports", icon: BarChart3, path: "/financials/reports" },
        { title: "Taxes", icon: TaxBuilding, path: "/financials/taxes" },
        { title: "Cost of Goods Sold (COGS)", icon: Coins, path: "/financials/cogs" },
        { title: "Financial Settings", icon: Settings, path: "/financials/settings" },
        { title: "Reconciliation", icon: CheckCircle, path: "/financials/reconciliation" },
      ],
    },
    {
      title: "API Dashboard",
      icon: Code,
      subMenu: [
        { title: "Overview", icon: LayoutDashboard, path: "/carrier-admin/api" },
        { title: "API Keys", icon: CreditCard, path: "/carrier-admin/api/keys" },
        { title: "API Logs", icon: FileText, path: "/carrier-admin/api/logs" },
        { title: "API Errors", icon: Bug, path: "/carrier-admin/api/errors" },
      ],
    },
    {
      title: "EDI Dashboard",
      icon: Zap,
      subMenu: [
        { title: "EDI Matching", icon: Activity, path: "/carrier-admin/edi/matching" },
        { title: "EDI Setup", icon: Settings, path: "/carrier-admin/edi/setup" },
        { title: "Partners List", icon: Users, path: "/carrier-admin/edi/partners" },
        { title: "Failed Tender", icon: AlertTriangle, path: "/carrier-admin/edi/failed/tender" },
        { title: "Failed Invoices", icon: XCircle, path: "/carrier-admin/edi/failed/invoices" },
      ],
    },
    {
      title: "Market Place",
      icon: Store,
      subMenu: [
        { title: "All", icon: Store, path: "/marketplace/all" },
        { title: "Accounting", icon: Calculator, path: "/marketplace/accounting" },
        { title: "Carrier Compliance", icon: ShieldAlert, path: "/marketplace/carrier-compliance" },
        { title: "API", icon: Code, path: "/marketplace/api" },
        { title: "EDI", icon: Zap, path: "/marketplace/edi" },
        { title: "ELDs", icon: Cpu, path: "/marketplace/elds" },
        { title: "Factoring", icon: DollarSign, path: "/marketplace/factoring" },
        { title: "Fuel Cards", icon: CreditCard, path: "/marketplace/fuel-cards" },
        { title: "Load Board", icon: Package, path: "/marketplace/load-board" },
        { title: "Mileage", icon: MapPin, path: "/marketplace/mileage" },
        { title: "Payments", icon: DollarSign, path: "/marketplace/payments" },
        { title: "Tolls", icon: MapPin, path: "/marketplace/tolls" },
        { title: "Visibility", icon: BarChart3, path: "/marketplace/visibility" },
      ],
    },
    {
      title: "Reports",
      icon: BarChart3,
      subMenu: [
        { title: "Dashboard", icon: BarChart3, path: "/carrier-admin/reports" },
        { title: "Financial Reports", icon: DollarSign, path: "/carrier-admin/reports/financial" },
        { title: "Operations Reports", icon: Activity, path: "/carrier-admin/reports/operations" },
        { title: "Performance Analytics", icon: TrendingUp, path: "/carrier-admin/reports/performance" },
        { title: "Driver Reports", icon: Users, path: "/carrier-admin/reports/drivers" },
        { title: "Vehicle Reports", icon: Truck, path: "/carrier-admin/reports/vehicles" },
        { title: "Route Analytics", icon: MapPin, path: "/carrier-admin/reports/routes" },
        { title: "Load Reports", icon: Package, path: "/carrier-admin/reports/loads" },
        { title: "Compliance Reports", icon: ShieldAlert, path: "/carrier-admin/reports/compliance" },
        { title: "Customer Reports", icon: Users, path: "/carrier-admin/reports/customers" },
        { title: "Safety Reports", icon: Shield, path: "/carrier-admin/reports/safety" },
        { title: "Fuel Reports", icon: Fuel, path: "/carrier-admin/reports/fuel" },
        { title: "Maintenance Reports", icon: Wrench, path: "/carrier-admin/reports/maintenance" },
        { title: "Custom Reports", icon: Settings, path: "/carrier-admin/reports/custom" },
      ],
    },
    {
      title: "Transportation Settings",
      icon: Settings,
      subMenu: [
        { title: "Trucking Operations", icon: Truck, path: "/carrier-admin/settings/trucking" },
        { title: "Freight Management", icon: Package, path: "/carrier-admin/settings/freight" },
        { title: "Logistics Network", icon: Globe, path: "/carrier-admin/settings/logistics" },
        { title: "Fleet Configuration", icon: Settings, path: "/carrier-admin/settings/fleet" },
        { title: "Route Optimization", icon: MapPin, path: "/carrier-admin/settings/routes" },
        { title: "Carrier Integration", icon: Building, path: "/carrier-admin/settings/carriers" },
        { title: "Mode Settings", icon: Truck, path: "/carrier-admin/settings/modes" },
      ],
    },
    {
      title: "Account Settings",
      icon: UserCheck,
      subMenu: [
        { title: "Profile Settings", icon: UserCheck, path: "/carrier-admin/settings/profile" },
        { title: "Company Settings", icon: Building, path: "/carrier-admin/settings/company" },
        { title: "Security Settings", icon: Shield, path: "/carrier-admin/settings/security" },
        { title: "Notification Settings", icon: Settings, path: "/carrier-admin/settings/notifications" },
        { title: "Integration Hub", icon: Zap, path: "/carrier-admin/settings/integrations" },
        { title: "Compliance Settings", icon: ShieldAlert, path: "/carrier-admin/settings/compliance" },
      ],
    },
  ],
};
