/* eslint-disable @typescript-eslint/no-explicit-any */

import { MenuSection } from '@/lib/types/menu';
import {
  LayoutDashboard,
  Heart,
  Mail,
  UserPlus,
  Contact,
  FolderOpen,
  Calendar,
  Target,
  DollarSign,
  Package,
  PackageSearch,
  PackagePlus,
  Truck,
  UserCheck,
  Clock,
  Building2,
  MapPin,
  Users,
  Upload,
  Settings,
  TrendingUp,
  Receipt,
  CreditCard,
  Calculator,
  PiggyBank,
  FileText,
  Banknote,
  Code,
  Bug,
  Zap,
  Store,
  ShieldAlert,
  Cpu,
  BarChart3,
  Plus,
  CheckCircle,
  RotateCcw,
  ShoppingCart,
  Landmark,
  BookOpen,
  Book,
  Scale,
  LineChart,
  Archive,
  Building,
  TrendingDown,
  Globe,
  Shield,
  Network,
  ClipboardList,
  Key,
  Activity,
  AlertTriangle,
  Repeat,
  ClipboardCheck,
  FileEdit,
  FilePlus,
  Handshake,
  ShieldCheck,
  Route,
  Eye,
  Layers,
  UserCircle,
  Briefcase,
  PlayCircle,
  Crown,
  Stethoscope,
  GraduationCap,
  Gauge,
  AlertCircle,
  ClipboardX,
  X
} from "lucide-react";

export const SHIPPER_ADMIN_MENU: MenuSection = {
  items: [
    {
      title: "Dashboard",
      icon: LayoutDashboard,
      path: "/shipper-admin/dashboard",
    },
    {
      title: "Shipments",
      icon: Package,
      subMenu: [
        { title: "All Shipments", icon: Package, path: "/shipper-admin/shipments/all" },
        { title: "New Shipment", icon: Plus, path: "/shipper-admin/shipments/new" },
        { title: "Assigned", icon: UserCheck, path: "/shipper-admin/shipments/assigned" },
        { title: "Pending", icon: Clock, path: "/shipper-admin/shipments/pending" },
        { title: "In Transit", icon: Truck, path: "/shipper-admin/shipments/in-transit" },
        { title: "Delivered", icon: CheckCircle, path: "/shipper-admin/shipments/delivered" },
      ],
    },
    {
      title: "Quotes",
      icon: DollarSign,
      subMenu: [
        { title: "All Quotes", icon: ClipboardList, path: "/shipper-admin/quotes/all" },
        { title: "New Quote", icon: Plus, path: "/shipper-admin/quotes/new" },
      ],
    },
    {
      title: "Load Board",
      icon: PackageSearch,
      subMenu: [
        { title: "Post Loads", icon: PackagePlus, path: "/shipper-admin/loadboard/post" },
        { title: "Search Loads", icon: PackageSearch, path: "/shipper-admin/loadboard/search" },
        { title: "Book Loads", icon: Handshake, path: "/shipper-admin/loadboard/book" },
      ],
    },
    {
      title: "Networks",
      icon: Network,
      subMenu: [
        { title: "Customers", icon: Users, path: "/shipper-admin/networks/customers" },
        { title: "Vendors", icon: Building, path: "/shipper-admin/networks/vendors" },
        { title: "Terminals", icon: Building2, path: "/shipper-admin/networks/terminals" },
        { title: "Locations", icon: MapPin, path: "/shipper-admin/networks/locations" },
      ],
    },
    {
      title: "CRM",
      icon: Heart,
      subMenu: [
        { title: "Overview", icon: BarChart3, path: "/shipper-admin/crm/overview" },
        { title: "Email", icon: Mail, path: "/shipper-admin/crm/emails" },
        { title: "Leads", icon: UserPlus, path: "/shipper-admin/crm/leads" },
        { title: "Contacts", icon: Contact, path: "/shipper-admin/crm/contacts" },
        { title: "Projects", icon: FolderOpen, path: "/shipper-admin/crm/projects" },
        { title: "Calendar", icon: Calendar, path: "/shipper-admin/crm/calendar" },
        { title: "Opportunities", icon: Target, path: "/shipper-admin/crm/opportunities" },
      ],
    },
    {
      title: "Financials",
      icon: DollarSign,
      subMenu: [
        { title: "Sales & Payments", icon: Receipt, path: "/shipper-admin/financials/sales-payments" },
        { title: "Invoices", icon: FileText, path: "/shipper-admin/financials/invoices" },
        { title: "Recurring Invoices", icon: Repeat, path: "/shipper-admin/financials/recurring-invoices" },
        { title: "Customer Statements", icon: ClipboardList, path: "/shipper-admin/financials/customer-statements" },
        { title: "Products & Services", icon: Package, path: "/shipper-admin/financials/products-services" },
        { title: "Purchases", icon: ShoppingCart, path: "/shipper-admin/financials/purchases" },
        { title: "Bills", icon: Receipt, path: "/shipper-admin/financials/bills" },
        { title: "Vendors", icon: Building, path: "/shipper-admin/financials/vendors" },
        { title: "Accounting", icon: Calculator, path: "/shipper-admin/financials/accounting" },
        { title: "Transactions", icon: Activity, path: "/shipper-admin/financials/transactions" },
        { title: "Reconciliation", icon: CheckCircle, path: "/shipper-admin/financials/reconciliation" },
        { title: "Chart of Accounts", icon: BookOpen, path: "/shipper-admin/financials/chart-accounts" },
        { title: "Payroll", icon: Banknote, path: "/shipper-admin/financials/payroll" },
        { title: "Run Payroll", icon: PlayCircle, path: "/shipper-admin/financials/run-payroll" },
        { title: "Employees", icon: Users, path: "/shipper-admin/financials/employees" },
        { title: "Timesheets", icon: Clock, path: "/shipper-admin/financials/timesheets" },
        { title: "Payroll Transactions", icon: Activity, path: "/shipper-admin/financials/payroll-transactions" },
        { title: "Taxes", icon: Scale, path: "/shipper-admin/financials/taxes" },
        { title: "Tax Forms", icon: FileText, path: "/shipper-admin/financials/tax-forms" },
      ],
    },
    {
      title: "Workers",
      icon: Users,
      subMenu: [
        { title: "Executive", icon: Crown, path: "/shipper-admin/workers/executive" },
        { title: "Employee", icon: UserCircle, path: "/shipper-admin/workers/employee" },
        { title: "Agents", icon: UserPlus, path: "/shipper-admin/workers/agents" },
      ],
    },
    {
      title: "Documents",
      icon: FileText,
      subMenu: [
        { title: "All Documents", icon: FolderOpen, path: "/shipper-admin/documents/all" },
        { title: "Upload", icon: Upload, path: "/shipper-admin/documents/upload" },
        { title: "Setup", icon: Settings, path: "/shipper-admin/documents/setup" },
      ],
    },
    {
      title: "Rates",
      icon: TrendingUp,
      subMenu: [
        { title: "Buy Rate", icon: DollarSign, path: "/shipper-admin/rates/buy" },
        { title: "Sell Rate", icon: TrendingUp, path: "/shipper-admin/rates/sell" },
      ],
    },
    {
      title: "API Dashboard",
      icon: Code,
      subMenu: [
        { title: "API Keys", icon: Key, path: "/shipper-admin/api/keys" },
        { title: "API Logs", icon: FileText, path: "/shipper-admin/api/logs" },
        { title: "API Errors", icon: AlertTriangle, path: "/shipper-admin/api/errors" },
      ],
    },
    {
      title: "EDI Dashboard",
      icon: Zap,
      subMenu: [
        { title: "EDI Matching", icon: Layers, path: "/shipper-admin/edi/matching" },
        { title: "EDI 210", icon: FileText, path: "/shipper-admin/edi/matching/210" },
        { title: "EDI 214", icon: FileEdit, path: "/shipper-admin/edi/matching/214" },
        { title: "EDI Setup", icon: Settings, path: "/shipper-admin/edi/setup" },
        { title: "Partners List", icon: Handshake, path: "/shipper-admin/edi/partners" },
        { title: "Failed", icon: AlertTriangle, path: "/shipper-admin/edi/failed" },
        { title: "Failed Tender", icon: ClipboardX, path: "/shipper-admin/edi/failed/tender" },
        { title: "Failed Invoices", icon: X, path: "/shipper-admin/edi/failed/invoices" },
      ],
    },
    {
      title: "Marketplace",
      icon: Store,
      subMenu: [
        { title: "All", icon: Store, path: "/shipper-admin/marketplace/all" },
        { title: "Accounting", icon: Calculator, path: "/shipper-admin/marketplace/accounting" },
        { title: "Carrier Compliance", icon: ShieldCheck, path: "/shipper-admin/marketplace/carrier-compliance" },
        { title: "API", icon: Code, path: "/shipper-admin/marketplace/api" },
        { title: "EDI", icon: Zap, path: "/shipper-admin/marketplace/edi" },
        { title: "ELDs", icon: Gauge, path: "/shipper-admin/marketplace/elds" },
        { title: "Factoring", icon: Banknote, path: "/shipper-admin/marketplace/factoring" },
        { title: "Fuel Cards", icon: CreditCard, path: "/shipper-admin/marketplace/fuel-cards" },
        { title: "Load Board", icon: PackageSearch, path: "/shipper-admin/marketplace/load-board" },
        { title: "Mileage", icon: Route, path: "/shipper-admin/marketplace/mileage" },
        { title: "Payments", icon: DollarSign, path: "/shipper-admin/marketplace/payments" },
        { title: "Tolls", icon: MapPin, path: "/shipper-admin/marketplace/tolls" },
        { title: "Visibility", icon: Eye, path: "/shipper-admin/marketplace/visibility" },
      ],
    },
    {
      title: "Reports",
      icon: BarChart3,
      subMenu: [
        { title: "Financial", icon: DollarSign, path: "/shipper-admin/reports/financial" },
        { title: "Receivable", icon: TrendingUp, path: "/shipper-admin/reports/receivable" },
        { title: "Payable", icon: TrendingDown, path: "/shipper-admin/reports/payable" },
        { title: "Banking", icon: Landmark, path: "/shipper-admin/reports/banking" },
        { title: "Payroll", icon: Banknote, path: "/shipper-admin/reports/payroll" },
        { title: "Sales", icon: LineChart, path: "/shipper-admin/reports/sales" },
      ],
    },
  ],
};
