
import { MenuSection } from '@/lib/types/menu';
  import {
  LayoutDashboard,
  Users,
  Heart,
  Mail,
  UserPlus,
  Contact,
  FolderOpen,
  Calendar,
  Target,
  Ticket,
  ShieldAlert,
  Bug,
  Settings,
  HelpCircle,
  Building2,
  Truck,
  UserCheck,
  FolderPlus,
  Upload,
  DollarSign,
  Receipt,
  CreditCard,
  ShoppingCart,
  Package,
  Calculator,
  PiggyBank,
  Clock,
  FileText,
  TrendingUp,
  Banknote,
  Zap,
  Code,
  BarChart3,
  Store,
  Briefcase,
  CreditCard as APIIcon,
  MapPin,
  Cpu,
  Plus,
  CheckCircle,
  RotateCcw,
  Landmark,
  BookOpen,
  Book,
  Scale,
  LineChart,
  Archive,
  Building,
  TrendingDown,
  Globe,
  Shield,
} from "lucide-react";

export const SUPER_ADMIN_MENU: MenuSection = {
  items: [
    {
      title: "Dashboard",
      icon: LayoutDashboard,
      path: "/dashboard",
    },
    {
      title: "Relationships",
      icon: Heart,
      subMenu: [
        { title: "Overview", icon: LayoutDashboard, path: "/crm/overview" },
        { title: "Email", icon: Mail, path: "/crm/emails" },
        { title: "Leads", icon: UserPlus, path: "/crm/leads" },
        { title: "Contacts", icon: Contact, path: "/crm/contacts" },
        { title: "Projects", icon: FolderOpen, path: "/crm/projects" },
        { title: "Calendar", icon: Calendar, path: "/crm/calendar" },
        { title: "Opportunities", icon: Target, path: "/crm/opportunities" },
      ],
    },
    {
      title: "Tickets",
      icon: Ticket,
      subMenu: [
        { title: "All Tickets", icon: Ticket, path: "/tickets/all" },
        { title: "Assigned", icon: UserCheck, path: "/tickets/assigned" },
        { title: "Unassigned", icon: Users, path: "/tickets/unassigned" },
        { title: "Incidents", icon: ShieldAlert, path: "/tickets/incidents" },
        { title: "Service Requests", icon: Settings, path: "/tickets/service-requests" },
        { title: "Changes", icon: HelpCircle, path: "/tickets/changes" },
        { title: "Problems", icon: Bug, path: "/tickets/problems" },
      ],
    },
    {
      title: "Shipments",
      icon: Package,
      subMenu: [
        { title: "All Shipments", icon: Package, path: "/shipments" },
        { title: "New Shipments", icon: Plus, path: "/shipments/new" },
        { title: "Assigned", icon: UserCheck, path: "/shipments/assigned" },
        { title: "Pending", icon: Clock, path: "/shipments/pending" },
        { title: "In Transit", icon: Truck, path: "/shipments/in-transit" },
        { title: "Delivered", icon: CheckCircle, path: "/shipments/delivered" },
      ],
    },
    {
      title: "Networks",
      icon: Building2,
      subMenu: [
        { title: "Customers", icon: Users, path: "/networks/customers" },
        { title: "Carriers", icon: Truck, path: "/networks/carriers" },
        { title: "Vendors", icon: Package, path: "/networks/vendors" },
        { title: "Terminals", icon: Building2, path: "/networks/terminals" },
        { title: "Locations", icon: MapPin, path: "/networks/locations" },
        { title: "Invoices", icon: Receipt, path: "/networks/invoices" },
      ],
    },
    {
      title: "Workers",
      icon: Users,
      subMenu: [
        { title: "Executive", icon: UserCheck, path: "/workers/executive" },
        { title: "Employee", icon: Users, path: "/workers/employee" },
        { title: "Drivers", icon: Truck, path: "/workers/drivers" },
        { title: "Agents", icon: UserPlus, path: "/workers/agents" },
      ],
    },
    {
      title: "Documents",
      icon: FileText,
      subMenu: [
        { title: "All Documents", icon: FolderOpen, path: "/documents/all" },
        { title: "Upload", icon: Upload, path: "/documents/upload" },
        { title: "Setup", icon: Settings, path: "/documents/setup" },
      ],
    },
    {
      title: "Financials",
      icon: DollarSign,
      subMenu: [
        { title: "Overview", icon: LayoutDashboard, path: "/financials" },
        {
          title: "Sales & Revenue",
          icon: TrendingUp,
          path: "/financials/sales",
          subMenu: [
            { title: "Invoices", icon: FileText, path: "/financials/sales/invoices" },
            { title: "Recurring Invoices", icon: RotateCcw, path: "/financials/sales/recurring-invoices" },
            { title: "Payments", icon: CreditCard, path: "/financials/sales/payments" },
            { title: "Quotes", icon: FileText, path: "/financials/sales/quotes" },
            { title: "Customer Statements", icon: Receipt, path: "/financials/sales/customer-statements" },
          ],
        },
        {
          title: "Expenses",
          icon: Receipt,
          path: "/financials/expenses",
          subMenu: [
            { title: "Bills", icon: Receipt, path: "/financials/expenses/bills" },
            { title: "Vendors", icon: Building2, path: "/financials/expenses/vendors" },
            { title: "Purchase Orders", icon: Package, path: "/financials/expenses/purchase-orders" },
            { title: "Expense Reports", icon: FileText, path: "/financials/expenses/expense-reports" },
          ],
        },
        {
          title: "Banking",
          icon: Landmark,
          path: "/financials/banking",
          subMenu: [
            { title: "Bank Accounts", icon: Banknote, path: "/financials/banking/bank-accounts" },
            { title: "Transactions", icon: Calculator, path: "/financials/banking/transactions" },
            { title: "Reconciliation", icon: CheckCircle, path: "/financials/banking/reconciliation" },
            { title: "Cash Flow", icon: TrendingUp, path: "/financials/banking/cash-flow" },
            { title: "Payroll", icon: Users, path: "/financials/payroll" },
          ],
        },
        {
          title: "Payroll",
          icon: Users,
          path: "/financials/payroll",
          subMenu: [
            { title: "Run Payroll", icon: PiggyBank, path: "/financials/payroll/run-payroll" },
            { title: "Employees", icon: UserCheck, path: "/financials/payroll/employees" },
            { title: "Timesheets", icon: Clock, path: "/financials/payroll/timesheets" },
            { title: "Payroll Reports", icon: BarChart3, path: "/financials/payroll/payroll-reports" },
            { title: "Benefits", icon: Shield, path: "/financials/payroll/benefits" },
            { title: "Tax Dashboard", icon: Calculator, path: "/financials/payroll/tax-dashboard" },
            { title: "Tax Returns", icon: FileText, path: "/financials/payroll/tax-returns" },
            { title: "Tax Payments", icon: DollarSign, path: "/financials/payroll/tax-payments" },
            { title: "Tax Forms", icon: FileText, path: "/financials/payroll/tax-forms" },
          ],
        },
        {
          title: "Reports",
          icon: BarChart3,
          path: "/financials/reports",
          subMenu: [
            { title: "Profit & Loss", icon: TrendingUp, path: "/financials/reports/profit-loss" },
            { title: "Balance Sheet", icon: Scale, path: "/financials/reports/balance-sheet" },
            { title: "Financial Dashboard", icon: BarChart3, path: "/financials/reports/dashboard" },
            { title: "Trial Balance", icon: Calculator, path: "/financials/reports/trial-balance" },
          ],
        },
        {
          title: "Settings",
          icon: Settings,
          path: "/financials/settings",
          subMenu: [
            { title: "Chart of Accounts", icon: BookOpen, path: "/financials/settings/chart-of-accounts" },
            { title: "Products & Services", icon: Package, path: "/financials/settings/products-services" },
            { title: "Tax Settings", icon: Calculator, path: "/financials/settings/tax-settings" },
          ],
        },
      ],
    },
    {
      title: "AI Dashboard",
      icon: Cpu,
      subMenu: [
        { title: "Analytics", icon: BarChart3, path: "/ai/analytics" },
        { title: "System Health", icon: Shield, path: "/ai/health" },
        { title: "Agent Control", icon: Users, path: "/ai/agents" },
        { title: "Autonomous System", icon: Settings, path: "/ai/autonomous-system" },
        { title: "Autonomous Agents", icon: Cpu, path: "/ai/autonomous-agents" },
        { title: "Agent Monitoring", icon: TrendingUp, path: "/ai/monitoring" },
        { title: "Design Engine", icon: Settings, path: "/ai/design-engine" },
        { title: "Market Research", icon: TrendingUp, path: "/ai/market-research" },
      ],
    },
    {
      title: "API Dashboard",
      icon: Code,
      subMenu: [
        { title: "Overview", icon: LayoutDashboard, path: "/api" },
        { title: "Keys", icon: Shield, path: "/api/keys" },
        { title: "Authentication", icon: Shield, path: "/api/authentication" },
        { title: "Analytics", icon: BarChart3, path: "/api/analytics" },
        { title: "Rate Limits", icon: Target, path: "/api/rate-limits" },
        { title: "Monitoring", icon: Bug, path: "/api/monitoring" },
      ],
    },
    {
      title: "Market Place",
      icon: Store,
      subMenu: [
        { title: "All", icon: Store, path: "/marketplace/all" },
        { title: "Accounting", icon: Calculator, path: "/marketplace/accounting" },
        { title: "Carrier Compliance", icon: ShieldAlert, path: "/marketplace/carrier-compliance" },
        { title: "API", icon: Code, path: "/marketplace/api" },
        { title: "EDI", icon: Zap, path: "/marketplace/edi" },
        { title: "ELDs", icon: Cpu, path: "/marketplace/elds" },
        { title: "Factoring", icon: DollarSign, path: "/marketplace/factoring" },
        { title: "Fuel Cards", icon: CreditCard, path: "/marketplace/fuel-cards" },
        { title: "Load Board", icon: Package, path: "/marketplace/load-board" },
        { title: "Mileage", icon: MapPin, path: "/marketplace/mileage" },
        { title: "Payments", icon: DollarSign, path: "/marketplace/payments" },
        { title: "Tolls", icon: MapPin, path: "/marketplace/tolls" },
        { title: "Visibility", icon: BarChart3, path: "/marketplace/visibility" },
      ],
    },
    {
      title: "Load Management",
      icon: Package,
      path: "/loads",
    },
    {
      title: "Carrier Dispatch",
      icon: Truck,
      path: "/carrier-dispatch",
    },
    {
      title: "Autonomous Agents",
      icon: Cpu,
      path: "/autonomous-agents",
    },
    {
      title: "Reports",
      icon: BarChart3,
      path: "/reports",
    },
  ],
};
