-- Add autonomous agent tasks for carrier onboarding, load board, and accounting functionality

INSERT INTO public.autonomous_tasks (task_id, agent_type, portal, task_name, description, priority, estimated_duration_minutes, dependencies, status) VALUES

-- CARRIER ONBOARDING TASKS (15 tasks)
('CAR_ONB_001', 'UI Builder', 'Super Admin', 'Carrier Registration Portal', 'Build multi-step carrier registration form with company info, DOT/MC numbers, insurance details, and contact information', 1, 180, ARRAY[]::text[], 'pending'),
('CAR_ONB_002', 'Data Processor', 'Super Admin', 'DOT Number Verification', 'Integrate with FMCSA API to verify DOT numbers and pull safety ratings automatically', 1, 120, ARRAY['CAR_ONB_001'], 'pending'),
('CAR_ONB_003', 'Security', 'Super Admin', 'Document Verification System', 'Build secure document upload and verification system for insurance, operating authority, and certifications', 1, 240, ARRAY['CAR_ONB_001'], 'pending'),
('CAR_ONB_004', 'Data Processor', 'Super Admin', 'Credit Check Integration', 'Integrate with credit reporting services for carrier financial assessment', 2, 150, ARRAY['CAR_ONB_001'], 'pending'),
('CAR_ONB_005', 'UI Builder', 'Super Admin', 'Onboarding Workflow Dashboard', 'Create admin dashboard for managing carrier onboarding pipeline with approval stages', 1, 200, ARRAY['CAR_ONB_001'], 'pending'),
('CAR_ONB_006', 'Data Processor', 'Super Admin', 'Auto-Approval Engine', 'Build AI-powered auto-approval system based on safety scores, insurance, and credit ratings', 2, 180, ARRAY['CAR_ONB_002', 'CAR_ONB_004'], 'pending'),
('CAR_ONB_007', 'UI Builder', 'Carrier', 'Carrier Portal Setup', 'Create initial carrier portal with profile completion tracking and document management', 1, 160, ARRAY['CAR_ONB_001'], 'pending'),
('CAR_ONB_008', 'Data Processor', 'Super Admin', 'Background Check Integration', 'Integrate driver background check services for carrier fleet verification', 2, 120, ARRAY['CAR_ONB_003'], 'pending'),
('CAR_ONB_009', 'UI Builder', 'Super Admin', 'Carrier Approval Notifications', 'Build notification system for approval status updates and required actions', 3, 90, ARRAY['CAR_ONB_005'], 'pending'),
('CAR_ONB_010', 'Data Processor', 'Super Admin', 'Fleet Size Verification', 'Verify carrier fleet size and equipment through multiple data sources', 2, 100, ARRAY['CAR_ONB_002'], 'pending'),
('CAR_ONB_011', 'Security', 'Super Admin', 'Carrier Contract Generation', 'Auto-generate carrier agreements based on approved terms and service types', 2, 140, ARRAY['CAR_ONB_006'], 'pending'),
('CAR_ONB_012', 'UI Builder', 'Super Admin', 'Onboarding Analytics Dashboard', 'Create analytics for onboarding conversion rates, approval times, and bottlenecks', 3, 120, ARRAY['CAR_ONB_005'], 'pending'),
('CAR_ONB_013', 'Data Processor', 'Super Admin', 'Insurance Expiration Monitoring', 'Monitor carrier insurance expiration dates and send renewal alerts', 2, 80, ARRAY['CAR_ONB_003'], 'pending'),
('CAR_ONB_014', 'UI Builder', 'Carrier', 'Onboarding Progress Tracker', 'Build progress tracking interface for carriers to see completion status', 3, 100, ARRAY['CAR_ONB_007'], 'pending'),
('CAR_ONB_015', 'Testing', 'All', 'Carrier Onboarding E2E Testing', 'Comprehensive testing of entire carrier onboarding workflow', 1, 200, ARRAY['CAR_ONB_001', 'CAR_ONB_005', 'CAR_ONB_007'], 'pending'),

-- LOAD BOARD TASKS (18 tasks)
('LOAD_BRD_001', 'UI Builder', 'Broker', 'Load Posting Interface', 'Build comprehensive load posting form with pickup/delivery details, equipment requirements, and rate information', 1, 160, ARRAY[]::text[], 'pending'),
('LOAD_BRD_002', 'UI Builder', 'Carrier', 'Load Search & Filter System', 'Create advanced search interface with filters for location, equipment type, rate, and distance', 1, 180, ARRAY[]::text[], 'pending'),
('LOAD_BRD_003', 'Data Processor', 'All', 'Load Matching Algorithm', 'Develop AI-powered load matching system based on carrier preferences, history, and performance', 1, 240, ARRAY['LOAD_BRD_001', 'LOAD_BRD_002'], 'pending'),
('LOAD_BRD_004', 'UI Builder', 'Carrier', 'Bidding System Interface', 'Build bidding interface for carriers to submit competitive bids on loads', 1, 140, ARRAY['LOAD_BRD_002'], 'pending'),
('LOAD_BRD_005', 'Data Processor', 'Broker', 'Auto-Award System', 'Create automated load award system based on predefined criteria and carrier rankings', 2, 160, ARRAY['LOAD_BRD_004'], 'pending'),
('LOAD_BRD_006', 'UI Builder', 'All', 'Real-time Load Board Updates', 'Implement real-time updates for load status, new postings, and bid notifications', 1, 200, ARRAY['LOAD_BRD_003'], 'pending'),
('LOAD_BRD_007', 'Data Processor', 'All', 'Route Optimization Integration', 'Integrate route optimization to suggest efficient load combinations and backhauls', 2, 180, ARRAY['LOAD_BRD_003'], 'pending'),
('LOAD_BRD_008', 'UI Builder', 'Broker', 'Load Management Dashboard', 'Create dashboard for brokers to manage posted loads, track bids, and award contracts', 1, 170, ARRAY['LOAD_BRD_001'], 'pending'),
('LOAD_BRD_009', 'Security', 'All', 'Load Board Access Controls', 'Implement security controls for load visibility based on carrier approval status and credit ratings', 1, 120, ARRAY['LOAD_BRD_002'], 'pending'),
('LOAD_BRD_010', 'Data Processor', 'All', 'Historical Rate Analytics', 'Build rate analytics showing historical pricing trends for lanes and equipment types', 2, 150, ARRAY['LOAD_BRD_003'], 'pending'),
('LOAD_BRD_011', 'UI Builder', 'Carrier', 'Favorite Loads & Alerts', 'Create system for carriers to save favorite lanes and receive alerts for matching loads', 3, 100, ARRAY['LOAD_BRD_002'], 'pending'),
('LOAD_BRD_012', 'Data Processor', 'All', 'Load Recommendation Engine', 'Develop ML-based recommendation system for suggesting relevant loads to carriers', 2, 200, ARRAY['LOAD_BRD_003'], 'pending'),
('LOAD_BRD_013', 'UI Builder', 'All', 'Mobile Load Board App', 'Create mobile-responsive load board interface for on-the-go access', 2, 220, ARRAY['LOAD_BRD_002', 'LOAD_BRD_004'], 'pending'),
('LOAD_BRD_014', 'Data Processor', 'Broker', 'Load Performance Analytics', 'Track load performance metrics including award time, carrier performance, and delivery success', 3, 130, ARRAY['LOAD_BRD_008'], 'pending'),
('LOAD_BRD_015', 'UI Builder', 'All', 'Load Communication Hub', 'Build messaging system for load-specific communication between brokers and carriers', 2, 160, ARRAY['LOAD_BRD_006'], 'pending'),
('LOAD_BRD_016', 'Data Processor', 'All', 'Capacity Forecasting', 'Develop capacity forecasting system to predict equipment availability and pricing', 3, 180, ARRAY['LOAD_BRD_010'], 'pending'),
('LOAD_BRD_017', 'Security', 'All', 'Load Board Fraud Detection', 'Implement fraud detection for fake loads, carriers, and suspicious bidding patterns', 2, 140, ARRAY['LOAD_BRD_009'], 'pending'),
('LOAD_BRD_018', 'Testing', 'All', 'Load Board E2E Testing', 'Comprehensive testing of load posting, bidding, and award workflow', 1, 180, ARRAY['LOAD_BRD_001', 'LOAD_BRD_004', 'LOAD_BRD_008'], 'pending'),

-- FULL ACCOUNTING FUNCTIONALITY TASKS (20 tasks)
('ACC_001', 'UI Builder', 'All', 'Chart of Accounts Setup', 'Build comprehensive chart of accounts configuration for transportation industry', 1, 160, ARRAY[]::text[], 'pending'),
('ACC_002', 'Data Processor', 'All', 'Automated Invoicing System', 'Create automated invoice generation based on completed shipments and rate confirmations', 1, 200, ARRAY['ACC_001'], 'pending'),
('ACC_003', 'UI Builder', 'All', 'Accounts Receivable Dashboard', 'Build AR dashboard with aging reports, payment tracking, and collection management', 1, 180, ARRAY['ACC_002'], 'pending'),
('ACC_004', 'Data Processor', 'All', 'Payment Processing Integration', 'Integrate multiple payment methods including ACH, wire transfers, and factoring', 1, 220, ARRAY['ACC_002'], 'pending'),
('ACC_005', 'UI Builder', 'All', 'Accounts Payable Management', 'Create AP system for carrier payments, fuel cards, and vendor management', 1, 190, ARRAY['ACC_001'], 'pending'),
('ACC_006', 'Data Processor', 'All', 'Automated Expense Categorization', 'Use AI to automatically categorize and code expenses from receipts and invoices', 2, 180, ARRAY['ACC_005'], 'pending'),
('ACC_007', 'UI Builder', 'All', 'Financial Reporting Suite', 'Build comprehensive financial reports including P&L, balance sheet, and cash flow', 1, 240, ARRAY['ACC_001'], 'pending'),
('ACC_008', 'Data Processor', 'All', 'Real-time Financial Analytics', 'Create real-time dashboards for key financial metrics and KPIs', 2, 160, ARRAY['ACC_007'], 'pending'),
('ACC_009', 'Security', 'All', 'Audit Trail System', 'Implement comprehensive audit trails for all financial transactions and changes', 1, 140, ARRAY['ACC_001'], 'pending'),
('ACC_010', 'Data Processor', 'All', 'Multi-Entity Accounting', 'Support multi-company and multi-location accounting with consolidation capabilities', 2, 200, ARRAY['ACC_001'], 'pending'),
('ACC_011', 'UI Builder', 'All', 'Tax Management System', 'Create tax calculation, reporting, and filing system for various jurisdictions', 2, 220, ARRAY['ACC_007'], 'pending'),
('ACC_012', 'Data Processor', 'All', 'Bank Reconciliation Automation', 'Automate bank statement reconciliation with intelligent transaction matching', 2, 160, ARRAY['ACC_004'], 'pending'),
('ACC_013', 'UI Builder', 'All', 'Budget Planning & Forecasting', 'Build budgeting tools with variance analysis and financial forecasting', 3, 180, ARRAY['ACC_007'], 'pending'),
('ACC_014', 'Data Processor', 'All', 'Cost Center Accounting', 'Implement cost center tracking for equipment, drivers, and business units', 2, 150, ARRAY['ACC_001'], 'pending'),
('ACC_015', 'Security', 'All', 'Financial Controls & Approvals', 'Create approval workflows for purchases, payments, and journal entries', 2, 130, ARRAY['ACC_005'], 'pending'),
('ACC_016', 'Data Processor', 'All', 'Revenue Recognition Automation', 'Automate revenue recognition based on delivery milestones and contract terms', 2, 170, ARRAY['ACC_002'], 'pending'),
('ACC_017', 'UI Builder', 'All', 'Factoring Integration', 'Build integration with factoring companies for invoice financing', 3, 140, ARRAY['ACC_003'], 'pending'),
('ACC_018', 'Data Processor', 'All', 'Financial Data Integration', 'Integrate with banks, credit card processors, and financial institutions', 2, 180, ARRAY['ACC_004'], 'pending'),
('ACC_019', 'UI Builder', 'All', 'CFO Executive Dashboard', 'Create executive-level financial dashboard with key metrics and alerts', 3, 160, ARRAY['ACC_008'], 'pending'),
('ACC_020', 'Testing', 'All', 'Accounting System E2E Testing', 'Comprehensive testing of all accounting workflows and integrations', 1, 240, ARRAY['ACC_002', 'ACC_005', 'ACC_007'], 'pending');