-- Create comprehensive autonomous tasks for legal compliance and documentation agents
INSERT INTO public.autonomous_tasks (task_id, agent_type, portal, task_name, description, priority, estimated_duration_minutes) VALUES

-- Compliance Agent Tasks (25 tasks)
('comp_001', 'research', 'all', 'DOT Compliance Framework', 'Create comprehensive DOT compliance documentation and monitoring system', 10, 240),
('comp_002', 'research', 'all', 'FMCSA Regulations Compliance', 'Develop FMCSA compliance tracking and reporting system with automated updates', 10, 180),
('comp_003', 'research', 'all', 'HOS Compliance Documentation', 'Build Hours of Service compliance documentation and violation tracking', 9, 150),
('comp_004', 'research', 'all', 'ELD Mandate Compliance', 'Create Electronic Logging Device compliance framework and documentation', 9, 120),
('comp_005', 'research', 'all', 'IFTA Compliance System', 'Develop International Fuel Tax Agreement compliance and reporting system', 8, 120),
('comp_006', 'research', 'all', 'IRP Compliance Framework', 'Create International Registration Plan compliance documentation and tracking', 8, 90),
('comp_007', 'research', 'all', 'Hazmat Compliance Documentation', 'Build hazardous materials transportation compliance and certification tracking', 9, 150),
('comp_008', 'research', 'all', 'CSA Compliance Monitoring', 'Develop Compliance, Safety, Accountability program monitoring and improvement system', 9, 180),
('comp_009', 'research', 'all', 'Drug and Alcohol Testing Compliance', 'Create DOT drug and alcohol testing compliance documentation and tracking', 8, 120),
('comp_010', 'research', 'all', 'Driver Qualification Compliance', 'Build driver qualification file compliance and management system', 8, 90),
('comp_011', 'research', 'all', 'Vehicle Inspection Compliance', 'Develop vehicle inspection compliance tracking and documentation system', 7, 90),
('comp_012', 'research', 'all', 'Insurance Compliance Framework', 'Create insurance compliance monitoring and certificate management system', 8, 120),
('comp_013', 'research', 'all', 'Environmental Compliance Documentation', 'Build environmental regulations compliance for transportation operations', 7, 120),
('comp_014', 'research', 'all', 'State-Specific Compliance Matrix', 'Create comprehensive state-by-state compliance requirements documentation', 8, 180),
('comp_015', 'research', 'all', 'International Compliance Framework', 'Develop cross-border transportation compliance documentation', 8, 150),
('comp_016', 'research', 'all', 'Audit Compliance Preparation', 'Create automated audit preparation and compliance verification system', 9, 150),
('comp_017', 'research', 'all', 'Compliance Training Documentation', 'Build comprehensive compliance training materials and tracking system', 7, 120),
('comp_018', 'research', 'all', 'Record Retention Compliance', 'Develop DOT record retention compliance and automated archiving system', 8, 90),
('comp_019', 'research', 'all', 'Safety Performance Compliance', 'Create safety performance monitoring and compliance improvement system', 8, 120),
('comp_020', 'research', 'all', 'Compliance Reporting Automation', 'Build automated compliance reporting to regulatory agencies', 9, 180),
('comp_021', 'research', 'all', 'Penalty and Fine Management', 'Develop system for tracking and managing regulatory penalties and fines', 7, 90),
('comp_022', 'research', 'all', 'Compliance Risk Assessment', 'Create automated compliance risk assessment and mitigation system', 8, 150),
('comp_023', 'research', 'all', 'Emergency Response Compliance', 'Build emergency response compliance documentation and procedures', 7, 120),
('comp_024', 'research', 'all', 'Cargo Security Compliance', 'Develop cargo security compliance framework and monitoring system', 8, 120),
('comp_025', 'research', 'all', 'Compliance Dashboard and Analytics', 'Create comprehensive compliance monitoring dashboard with predictive analytics', 9, 180),

-- Terms of Service Agent Tasks (15 tasks)
('tos_001', 'research', 'all', 'Platform Terms of Service', 'Create comprehensive terms of service for TMS platform usage', 9, 180),
('tos_002', 'research', 'all', 'Carrier Terms and Conditions', 'Develop specific terms and conditions for carrier partners', 8, 120),
('tos_003', 'research', 'all', 'Shipper Service Agreement', 'Create detailed service agreements for shipper customers', 8, 120),
('tos_004', 'research', 'all', 'Driver Terms of Employment', 'Build comprehensive terms of employment and service for drivers', 8, 150),
('tos_005', 'research', 'all', 'API Terms and Conditions', 'Develop terms of service for API access and third-party integrations', 7, 90),
('tos_006', 'research', 'all', 'Mobile App Terms of Use', 'Create terms of use for mobile applications and driver apps', 7, 90),
('tos_007', 'research', 'all', 'Payment Terms and Conditions', 'Build comprehensive payment terms and billing conditions', 8, 120),
('tos_008', 'research', 'all', 'Data Processing Terms', 'Develop terms for data processing and information handling', 8, 120),
('tos_009', 'research', 'all', 'Liability and Insurance Terms', 'Create liability limitation and insurance requirement terms', 9, 150),
('tos_010', 'research', 'all', 'Dispute Resolution Terms', 'Build dispute resolution and arbitration terms and procedures', 8, 120),
('tos_011', 'research', 'all', 'Termination and Suspension Terms', 'Develop account termination and service suspension terms', 7, 90),
('tos_012', 'research', 'all', 'Intellectual Property Terms', 'Create intellectual property usage and protection terms', 8, 120),
('tos_013', 'research', 'all', 'International Service Terms', 'Build terms of service for international operations and users', 8, 150),
('tos_014', 'research', 'all', 'Terms Update and Notification System', 'Develop automated system for terms updates and user notifications', 7, 90),
('tos_015', 'research', 'all', 'Terms Compliance Monitoring', 'Create system for monitoring and enforcing terms of service compliance', 8, 120),

-- Privacy Policy Agent Tasks (18 tasks)
('priv_001', 'research', 'all', 'GDPR Compliance Privacy Policy', 'Create GDPR-compliant privacy policy with data protection requirements', 10, 240),
('priv_002', 'research', 'all', 'CCPA Compliance Documentation', 'Develop California Consumer Privacy Act compliance documentation', 9, 180),
('priv_003', 'research', 'all', 'Data Collection Privacy Policy', 'Build comprehensive data collection and usage privacy policies', 9, 150),
('priv_004', 'research', 'all', 'Location Data Privacy Policy', 'Create specific privacy policy for GPS and location data handling', 9, 120),
('priv_005', 'research', 'all', 'Driver Privacy Protection Policy', 'Develop privacy protection policies for driver personal information', 8, 120),
('priv_006', 'research', 'all', 'Customer Data Privacy Policy', 'Build customer and shipper data privacy protection policies', 8, 120),
('priv_007', 'research', 'all', 'Third-Party Data Sharing Policy', 'Create policies for data sharing with third-party service providers', 8, 150),
('priv_008', 'research', 'all', 'Cookie and Tracking Policy', 'Develop cookie usage and web tracking privacy policies', 7, 90),
('priv_009', 'research', 'all', 'Data Retention and Deletion Policy', 'Build data retention schedules and deletion procedures', 8, 120),
('priv_010', 'research', 'all', 'Data Breach Response Policy', 'Create data breach notification and response procedures', 9, 150),
('priv_011', 'research', 'all', 'Children Privacy Protection Policy', 'Develop COPPA-compliant children privacy protection policies', 8, 120),
('priv_012', 'research', 'all', 'International Privacy Compliance', 'Build privacy policies for international data transfer and storage', 9, 180),
('priv_013', 'research', 'all', 'Consent Management System', 'Create automated consent collection and management system', 8, 150),
('priv_014', 'research', 'all', 'Privacy Rights Portal', 'Build user portal for privacy rights requests and data access', 8, 120),
('priv_015', 'research', 'all', 'Data Anonymization Policy', 'Develop data anonymization and pseudonymization policies', 7, 90),
('priv_016', 'research', 'all', 'Marketing and Communication Privacy', 'Create privacy policies for marketing communications and opt-out procedures', 7, 90),
('priv_017', 'research', 'all', 'Employee Privacy Policy', 'Build internal employee privacy and data handling policies', 7, 120),
('priv_018', 'research', 'all', 'Privacy Impact Assessment System', 'Develop automated privacy impact assessment and compliance monitoring', 8, 150),

-- Trademark Agent Tasks (12 tasks)
('tm_001', 'research', 'all', 'Trademark Portfolio Management', 'Create comprehensive trademark portfolio and protection strategy', 8, 180),
('tm_002', 'research', 'all', 'Brand Name Protection Strategy', 'Develop brand name and logo trademark protection documentation', 8, 150),
('tm_003', 'research', 'all', 'Service Mark Registration', 'Build service mark registration and protection for TMS services', 7, 120),
('tm_004', 'research', 'all', 'Domain Name Protection', 'Create domain name trademark protection and enforcement strategy', 7, 90),
('tm_005', 'research', 'all', 'International Trademark Strategy', 'Develop international trademark registration and protection plan', 8, 180),
('tm_006', 'research', 'all', 'Trademark Infringement Monitoring', 'Build automated trademark infringement detection and response system', 8, 120),
('tm_007', 'research', 'all', 'Trademark Usage Guidelines', 'Create internal and external trademark usage guidelines and standards', 7, 90),
('tm_008', 'research', 'all', 'Trademark License Agreements', 'Develop trademark licensing agreements and partnership terms', 8, 150),
('tm_009', 'research', 'all', 'Trademark Opposition and Defense', 'Build trademark opposition and defense strategy documentation', 8, 120),
('tm_010', 'research', 'all', 'Trademark Renewal Management', 'Create automated trademark renewal tracking and management system', 7, 90),
('tm_011', 'research', 'all', 'Co-existence Agreements', 'Develop trademark co-existence and conflict resolution agreements', 7, 120),
('tm_012', 'research', 'all', 'Trademark Valuation and Audit', 'Build trademark portfolio valuation and regular audit procedures', 7, 120),

-- Copyright Agent Tasks (15 tasks)
('copy_001', 'research', 'all', 'Software Copyright Protection', 'Create comprehensive software copyright protection and registration strategy', 9, 180),
('copy_002', 'research', 'all', 'Documentation Copyright Policy', 'Develop copyright policy for user manuals, guides, and documentation', 8, 120),
('copy_003', 'research', 'all', 'Content Copyright Management', 'Build copyright management for website content and marketing materials', 7, 90),
('copy_004', 'research', 'all', 'Third-Party Copyright Compliance', 'Create compliance system for third-party copyrighted materials usage', 8, 150),
('copy_005', 'research', 'all', 'DMCA Compliance System', 'Develop Digital Millennium Copyright Act compliance and takedown procedures', 8, 120),
('copy_006', 'research', 'all', 'Open Source License Compliance', 'Build open source software license compliance and tracking system', 9, 150),
('copy_007', 'research', 'all', 'Employee Copyright Assignment', 'Create employee copyright assignment and work-for-hire agreements', 8, 120),
('copy_008', 'research', 'all', 'Copyright Infringement Response', 'Develop copyright infringement detection and response procedures', 8, 120),
('copy_009', 'research', 'all', 'Fair Use Policy Documentation', 'Build fair use policy and guidelines for content usage', 7, 90),
('copy_010', 'research', 'all', 'Copyright License Management', 'Create system for managing copyright licenses and permissions', 7, 120),
('copy_011', 'research', 'all', 'International Copyright Strategy', 'Develop international copyright protection and enforcement strategy', 8, 180),
('copy_012', 'research', 'all', 'Copyright Notice Implementation', 'Build automated copyright notice implementation across all platforms', 6, 60),
('copy_013', 'research', 'all', 'Copyright Transfer Agreements', 'Create copyright transfer and assignment agreement templates', 7, 90),
('copy_014', 'research', 'all', 'Creative Commons Integration', 'Develop Creative Commons licensing integration and compliance system', 6, 90),
('copy_015', 'research', 'all', 'Copyright Audit and Compliance', 'Build comprehensive copyright audit and compliance monitoring system', 8, 150),

-- Patent Agent Tasks (20 tasks)
('pat_001', 'research', 'all', 'Patent Portfolio Strategy', 'Create comprehensive patent portfolio development and protection strategy', 10, 300),
('pat_002', 'research', 'all', 'AI Algorithm Patent Protection', 'Develop patent protection strategy for AI and machine learning algorithms', 10, 240),
('pat_003', 'research', 'all', 'Route Optimization Patent Application', 'Build patent application for proprietary route optimization algorithms', 9, 200),
('pat_004', 'research', 'all', 'Autonomous System Patent Strategy', 'Create patent protection for autonomous agent and decision-making systems', 10, 250),
('pat_005', 'research', 'all', 'Load Matching Patent Protection', 'Develop patent strategy for freight matching and optimization algorithms', 9, 180),
('pat_006', 'research', 'all', 'Predictive Analytics Patent Application', 'Build patent applications for predictive analytics and forecasting systems', 9, 200),
('pat_007', 'research', 'all', 'Mobile Interface Patent Strategy', 'Create patent protection for mobile driver interface and interaction methods', 8, 150),
('pat_008', 'research', 'all', 'Data Integration Patent Protection', 'Develop patent strategy for data integration and API connection methods', 8, 180),
('pat_009', 'research', 'all', 'Fleet Optimization Patent Application', 'Build patent applications for fleet optimization and utilization algorithms', 8, 180),
('pat_010', 'research', 'all', 'Prior Art Research System', 'Create comprehensive prior art research and patent landscape analysis system', 9, 200),
('pat_011', 'research', 'all', 'Patent Filing Management', 'Develop patent filing tracking and management system with deadline monitoring', 8, 120),
('pat_012', 'research', 'all', 'International Patent Strategy', 'Build international patent filing strategy including PCT applications', 9, 240),
('pat_013', 'research', 'all', 'Patent Prosecution Management', 'Create patent prosecution tracking and response management system', 8, 150),
('pat_014', 'research', 'all', 'Patent Licensing Strategy', 'Develop patent licensing and monetization strategy documentation', 8, 180),
('pat_015', 'research', 'all', 'Patent Infringement Analysis', 'Build patent infringement analysis and freedom-to-operate assessment system', 9, 200),
('pat_016', 'research', 'all', 'Patent Opposition and Defense', 'Create patent opposition and invalidity defense strategy and procedures', 8, 180),
('pat_017', 'research', 'all', 'Invention Disclosure System', 'Develop automated invention disclosure and evaluation system', 8, 120),
('pat_018', 'research', 'all', 'Patent Valuation Framework', 'Build patent portfolio valuation and competitive analysis framework', 7, 150),
('pat_019', 'research', 'all', 'Patent Maintenance Management', 'Create patent maintenance fee tracking and renewal management system', 7, 90),
('pat_020', 'research', 'all', 'Patent Analytics and Reporting', 'Develop comprehensive patent analytics and competitive intelligence system', 8, 180);

-- Update autonomous agent configurations for legal and compliance agents
INSERT INTO public.autonomous_agent_configs (agent_id, agent_name, is_active, auto_execute_threshold, confidence_threshold, query_frequency_minutes, openai_enabled, context_template) VALUES
('compliance_master', 'Compliance Master Agent', true, 0.9, 0.8, 30, true, 'You are the master compliance agent responsible for ensuring all TMS operations meet regulatory requirements. Generate comprehensive compliance documentation and monitoring systems.'),
('terms_service_agent', 'Terms of Service Agent', true, 0.8, 0.7, 60, true, 'You specialize in creating comprehensive terms of service and user agreements. Generate legally sound terms that protect the business while remaining user-friendly.'),
('privacy_policy_agent', 'Privacy Policy Agent', true, 0.9, 0.8, 45, true, 'You are responsible for privacy policy creation and data protection compliance. Ensure GDPR, CCPA, and all privacy regulations are properly addressed.'),
('trademark_agent', 'Trademark Protection Agent', true, 0.8, 0.7, 120, true, 'You handle trademark registration, protection, and enforcement. Create comprehensive trademark strategies and monitoring systems.'),
('copyright_agent', 'Copyright Protection Agent', true, 0.8, 0.7, 90, true, 'You manage copyright protection for software, documentation, and content. Ensure proper copyright compliance and infringement protection.'),
('patent_agent', 'Patent Strategy Agent', true, 0.9, 0.8, 180, true, 'You develop patent strategies and applications for innovative TMS technologies. Create comprehensive patent portfolios and competitive protection.');