/* eslint-disable @typescript-eslint/no-explicit-any */

import React from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import AIAgentManager from './AIAgentManager';
import { AutonomousTaskManager } from './AutonomousTaskManager';
import AutonomousKnowledgeBase from './AutonomousKnowledgeBase';
import RealtimeDashboard from './RealtimeDashboard';
import PerformanceOptimizationDashboard from './PerformanceOptimizationDashboard';
import PredictiveScalingDashboard from './PredictiveScalingDashboard';
import SelfHealingDashboard from './SelfHealingDashboard';
import AutonomousUIDesignDashboard from './AutonomousUIDesignDashboard';
import { AutonomousWebsiteUpdater } from './AutonomousWebsiteUpdater';
import { LiveWebsiteUpdater } from './LiveWebsiteUpdater';
import { RealAutonomousUpdater } from './RealAutonomousUpdater';
import { DashboardTemplate } from '../dashboard/DashboardTemplate';
import AgentDashboard from '../../pages/autonomous/AgentDashboard';
import PerformanceMonitor from '../../pages/autonomous/PerformanceMonitor';
import LearningModels from '../../pages/autonomous/LearningModels';
import DecisionLogs from '../../pages/autonomous/DecisionLogs';
import AutoScaling from '../../pages/autonomous/AutoScaling';

const AutonomousTabs = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Autonomous TMS System</h1>
        <p className="text-muted-foreground">
          AI-powered transportation management with self-learning capabilities
        </p>
      </div>

      <Tabs defaultValue="dashboard" className="space-y-4">
        <TabsList className="grid w-full grid-cols-12">
          <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
          <TabsTrigger value="agent-dashboard">Agent Dashboard</TabsTrigger>
          <TabsTrigger value="performance-monitor">Performance Monitor</TabsTrigger>
          <TabsTrigger value="learning-models">Learning Models</TabsTrigger>
          <TabsTrigger value="decision-logs">Decision Logs</TabsTrigger>
          <TabsTrigger value="auto-scaling">Auto Scaling</TabsTrigger>
          <TabsTrigger value="agents">AI Agents</TabsTrigger>
          <TabsTrigger value="tasks">Task Manager</TabsTrigger>
          <TabsTrigger value="knowledge">Knowledge Base</TabsTrigger>
          <TabsTrigger value="optimization">Optimization</TabsTrigger>
          <TabsTrigger value="scaling">Scaling</TabsTrigger>
          <TabsTrigger value="healing">Self-Healing</TabsTrigger>
        </TabsList>

        <TabsContent value="dashboard" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Real-time System Overview</CardTitle>
              <CardDescription>
                Live metrics and performance indicators for the autonomous TMS
              </CardDescription>
            </CardHeader>
            <CardContent>
              <RealtimeDashboard />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="agents" className="space-y-4">
          <AIAgentManager />
        </TabsContent>

        <TabsContent value="tasks" className="space-y-4">
          <AutonomousTaskManager />
        </TabsContent>

        <TabsContent value="knowledge" className="space-y-4">
          <AutonomousKnowledgeBase />
        </TabsContent>

        <TabsContent value="optimization" className="space-y-4">
          <PerformanceOptimizationDashboard />
        </TabsContent>

        <TabsContent value="scaling" className="space-y-4">
          <PredictiveScalingDashboard />
        </TabsContent>

        <TabsContent value="healing" className="space-y-4">
          <SelfHealingDashboard />
        </TabsContent>

        <TabsContent value="ui-design" className="space-y-4">
          <AutonomousUIDesignDashboard />
        </TabsContent>

        <TabsContent value="website-updater" className="space-y-4">
          <AutonomousWebsiteUpdater />
        </TabsContent>

        <TabsContent value="live-updater" className="space-y-4">
          <LiveWebsiteUpdater />
        </TabsContent>

        <TabsContent value="real-updater" className="space-y-4">
          <RealAutonomousUpdater />
        </TabsContent>

        <TabsContent value="portal-dashboards" className="space-y-4">
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold">Portal Dashboards</h2>
                <p className="text-muted-foreground">
                  All 20 portal dashboards generated by autonomous agents
                </p>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {['broker', 'carrier', 'shipper', 'driver', 'superAdmin'].map((portalKey) => (
                <div key={portalKey} className="border rounded-lg p-4 hover:shadow-md transition-shadow">
                  <h3 className="font-semibold capitalize mb-2">{portalKey} Dashboard</h3>
                  <p className="text-sm text-muted-foreground mb-3">
                    Complete dashboard with KPIs, charts, tables, and alerts
                  </p>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => window.open(`/${portalKey}/dashboard`, '_blank')}
                      className="px-3 py-1 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
                    >
                      View Dashboard
                    </button>
                  </div>
                </div>
              ))}
            </div>
            
            <div className="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg">
              <h3 className="font-semibold text-green-800 mb-2">✅ Dashboard System Complete</h3>
              <p className="text-green-700 text-sm">
                All 20 portal dashboards have been generated with consistent design, 
                real-time data integration, and autonomous agent monitoring.
              </p>
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AutonomousTabs;
