
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imcyiofodlnbomemvqto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltY3lpb2ZvZGxuYm9tZW12cXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzUzODUsImV4cCI6MjA2NTcxMTM4NX0.f0ylKsa3JtCqC3wW0YsnEVA1-zW-Fs7EE2KABU_81H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
